model_list:
  
  - model_name: openai-gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_APIKEY #read from env 
      temperature: 0.2
  - model_name: mistral-large-latest
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: os.environ/MISTRAL_APIKEY # read from env
      temperature: 0.2

litellm_settings:
  callbacks: custom_callbacks.proxy_handler_instance
